### ISSUE TITLE
Any chance of an update to 440.59 for EL7? We're still on 440.44 .. :)

### ISSUE THREAD

**Issue by ElCoyote27** [negativo17/nvidia-kmod#10]
I was wondering if there was anything we could help with to get 440.31 on EL7? The latest kmod seems to be 430.50 for EL7.

**Comment by scaronni** [comment]
I'm planning to do in the next days for all supported distributions since this is now a long lived release.

"still"... the release is 4 days old :)

**Comment by ElCoyote27** [comment]
Do you need any help? The reason why I am asking is that I've been chasing frequent crashdumps on 430.50 on EL7 and would -love- to move to something else.
I searched your git repos but I couldn't find any kind of toolchain (to split NVidia's .run package into sub tarballs so that you can rebuild the various nvidia-*src.rpm separately.

**Comment by ElCoyote27** [comment]
Got the update today.. Looks good on RHEL7.7.
Thank you so much..

**Comment by ElCoyote27** [comment]
Hurray! 440.59 released today mentions in its release notes:
`- Fixed a bug that could cause the X server to crash while exiting DPMS with HardDPMS enabled.`
Can't wait to get my hands on this one.. :)

**Comment by ElCoyote27** [comment]
@scaronni Thank you for your continued support. :) I still have a few machines on EL7 which benefit greatly from your builds.
Thank you so much.
