### ISSUE TITLE
No secureboot key listed as stated in documenation

### ISSUE THREAD

**Issue by AkashKrx** [negativo17/nvidia-kmod#13]
As per this comment https://negativo17.org/nvidia-driver/#comment-55819

> If you use DKMS, you just need to import the DKMS key: /var/lib/dkms/mok.pub
> 
> DKMS already signs all built modules with a per system unique key by default.
> 
> If you use akmods, you need to import this: /usr/src/akmods/mok.der
> 
> This is a custom addition I added to the AKMOD: https://github.com/negativo17/nvidia-kmod/blob/master/nvidia-kmod.spec#L19-L27

**There is no such file in /usr/src/akmods/mok.der**

**Comment by scaronni** [comment]
Have you opened a bug on a comment? :laughing: 

akmods has changed location of the certificate: https://rpmfusion.org/Howto/Secure%20Boot#Importing_the_key
