### ISSUE TITLE
Please use a better patch for 4.10 kernel

### ISSUE THREAD

**Issue by leigh123linux** [negativo17/nvidia-kmod#3]
Please use a better patch for 4.10 kernel as the current patches suck.

375.39 or 378.13

https://pkgs.rpmfusion.org/cgit/nonfree/nvidia-kmod.git/tree/kernel_4.10.patch

340.102

https://pkgs.rpmfusion.org/cgit/nonfree/nvidia-340xx-kmod.git/tree/4.10.0_kernel.patch

The ubuntu patches are far better than those horrible hacks from the nvidia forum.

**Comment by scaronni** [comment]
Thank you!
Hopefully all of this will not be needed soon and there will be only one place where to apply the patch :)
