### ISSUE TITLE
nvidia 378.x series doesn't support some recent hardware

### ISSUE THREAD

**Issue by jhoblitt** [negativo17/nvidia-kmod#5]
I have a ~1 year old Dell xps15 laptop w/ a 960M GPU.

```
# lspci -s 01:00.0 -v
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 960M] (rev a2)
	Subsystem: Dell Device 06e4
	Flags: fast devsel, IRQ 16
	[virtual] Memory at dc000000 (32-bit, non-prefetchable) [size=16M]
	Memory at b0000000 (64-bit, prefetchable) [size=256M]
	Memory at c0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	[virtual] Expansion ROM at dd000000 [disabled] [size=512K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable- Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Endpoint, MSI 00
	Capabilities: [100] Virtual Channel
	Capabilities: [250] Latency Tolerance Reporting
	Capabilities: [258] L1 PM Substates
	Capabilities: [128] Power Budgeting <?>
	Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
	Capabilities: [900] #19
	Kernel modules: nouveau, nvidia_drm, nvidia
```

Nvidia, in their infinite wisdom, has dropped support for this GPU from the 378.x series.  According to their driver search page, 375.39 is the latest driver to support my hardware.

Is there any acceptable way of adding this driver series into this repo?  Perhaps as additional branches.  Eg, `fedora-25-375`

**Comment by scaronni** [comment]
> Nvidia, in their infinite wisdom, has dropped support for this GPU from the 378.x series. According to their driver search page, 375.39 is the latest driver to support my hardware.

Actually I see it as supported on the 378.13 release:

http://www.nvidia.com/Download/driverResults.aspx/115031/en-us
http://us.download.nvidia.com/XFree86/Linux-x86_64/378.13/README/supportedchips.html

I would be pretty surprised if they wouldn't.

**Comment by jhoblitt** [comment]
Eh, weird. Under f25, 378.13 was printing errors in my dmesg the my pci id was unsupported.  I upgraded to `4.9.10-200.fc25.x86_64` and it is now loading.  Sorry for the noise...
