### ISSUE TITLE
latest kmod-nvidia issues with RHEL 7.5

### ISSUE THREAD

**Issue by ElCoyote27** [negativo17/nvidia-kmod#7]
Hi,
Just updated to RHEL 7.5 and it seems the kmod-nvidia rpm might need to be recompiled:
# /sbin/weak-modules --no-initramfs --add-kernel 3.10.0-862.el7.x86_64 --verbose
[...]
Module nvidia-uvm.ko from kernel 3.10.0-693.el7.x86_64 is not compatible with kernel 3.10.0-862.el7.x86_64 in symbols:  radix_tree_insert
Module nvidia.ko from kernel 3.10.0-693.el7.x86_64 is not compatible with kernel 3.10.0-862.el7.x86_64 in symbols:  efi_enabled screen_info i2c_del_adapter i2c_add_adapter acpi_bus_unregister_driver acpi_bus_get_device acpi_bus_register_driver
Module nvidia-modeset.ko from kernel 3.10.0-693.el7.x86_64 is not compatible with kernel 3.10.0-862.el7.x86_64 in symbols:  nv_kthread_q_flush nvidia_register_module nv_kthread_q_schedule_q_item nvidia_get_rm_ops nv_kthread_q_item_init nv_kthread_q_stop nvidia_unregister_module nv_kthread_q_init

**Comment by schulzj01** [comment]
Can verify that this is an issue. Latest kernel update no longer starting gnome.

**Comment by scaronni** [comment]
Solved long time ago.
