### ISSUE TITLE
Latest kmod-nvidia on el7 pulls down el7.6 kernel on el7.7

### ISSUE THREAD

**Issue by ElCoyote27** [negativo17/nvidia-kmod#8]
Hi,
First of all, thank you so much for making these packages available. I've been using your packages on EL7 and Fedora and couldn't imagine my digital life without them.

Just this morning, I was updating packages and I noticed that the latest kmod-nvidia (under https://negativo17.org/repos/nvidia/epel-7/x86_64) pulled down the most recent el7.6 kernel on my previously working el7.7 system.
Fix was easy: Download the src.rpm for kmod-nvidia and kmod-nvidia-common and rebuild on el7.7.
Now that Centos7.7 is out, are you planning on updating the builds anytime soon?
Thank you so much,
Vincent

**Comment by scaronni** [comment]
Argh, that was a mistake, I forgot to bump the minimum version required in the spec file and symbols changed between 7.6/7.7.

Will fix in a few hours.

**Comment by ElCoyote27** [comment]
Hey, no problem. This was only a minor annoyance. Thank you so much once again for these packages.

**Comment by scaronni** [comment]
Just pushed. Please close if it's fine.

**Comment by ElCoyote27** [comment]
Yes, I can confirm that it is fine now with: kmod-nvidia-430.50-2.el7.x86_64
